# -*- coding: utf-8 -*-
"""GreenhouseGasMissouriWyoming

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dA4Fph6cCec9BgtEyx_gylLRou3lucJ7
"""

import pandas as pd
import numpy as np
import glob
import os

# Path to the directory containing the CSV files
dir_path = "/content/StateData"

# Dictionary to store the DataFrames
dataframes = {}

# Loop through each file in the directory
for file_name in os.listdir(dir_path):
    if file_name.endswith('.csv'):
        # Construct the full file path
        file_path = os.path.join(dir_path, file_name)
        
        # Get the filename without the extension
        filename = os.path.splitext(file_name)[0]
        
        # Create a DataFrame from the CSV file
        df = pd.read_csv(file_path)
        
        # Store the DataFrame in the dictionary with a unique name
        dataframes[filename + "df"] = df
        
        # Do something with the DataFrame, e.g. print the first few rows
        #print(dataframes[filename + "df"].head())

dataframes['UtahDatadf']



